# Spring
server:
  port: 0
spring:
  application:
    name: product-service
# MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: estore

# Eureka
eureka:
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka